### PR TITLE
Tweak Usage Messages

### PR DESCRIPTION
**Pull request by chin-herng**
This PR mainly tweaks the usage message of commands for which mass ops is supported. The usage messages currently state that the provided indices must be distinct, yet the mass ops commands are actually able to remove duplicate indices. As such, the distinctness requirement in the usage messages will be removed, widening the scope of these messages.

Additionally, the success message string constant for each command are also renamed to be consistent with each other, as an attempt to improve code quality. Note that this just changes the names of several variables internally, and does not change any text in the UI at all.

### CODE REVIEW

**Review by nobodyishappy — APPROVED** [review]
LGTM

**Review by breezetall — APPROVED** [review]
LGTM!

**Review by Kaya3842 — APPROVED** [review]
LGTM!

**Review by Yskie — APPROVED** [review]
lgtm, merging.

**Pull request merged**
