### PR TITLE
Add personal tasks

### PR DESCRIPTION
**Pull request by Kaya3842**
As a student, I can add personal tasks, so that I can keep up to date with the different tasks to complete.

### CODE REVIEW

**Comment by Yskie** [comment]
Looks good to me!

**Comment by nobodyishappy** [comment]
Looks great! Would be good to include a task name for the task.

**Review by breezetall — COMMENTED** [review]
LGM!

**Review by chin-herng — APPROVED** [review]
LGTM! Thanks for the hard work and apologies for the late review.

**Pull request merged**
