### PR TITLE
Assign Tasks to Persons

### PR DESCRIPTION
**Pull request by chin-herng**
# The `Assign` Command

Instead of `tags`, `Person` now has `tasks`. The `assign` command assigns tasks to people in the address book. The command has the following format:

```
assign TASK_NUMBER to/ PERSON_NUMBER
```

Parameter: `TASK_NUMBER`

- Must be a numeric string representing a number between 1 and number of tasks.
- If the value is not acceptable, the error message `The task index provided is invalid` is displayed.

Parameter: `PERSON_NUMBER`

- Must be a numeric string representing a number between 1 and number of persons in the filtered person view.
- If the value is not acceptable, the error message `The person index provided is invalid` is displayed.

If the person is already assigned the task, the command is still accepted and succeeds.

## Things to note

- `edit` command does not allow editing tasks. The `assign` command is used to edit tasks for a person.
- `add` command does not allow assigning tasks straight away. The `assign` command has to be used after an `add` to assign tasks to a newly added person.
- `Task` is currently being hashed by `description`. Moving on, we will be adding `name` to `Task`, after which it makes more sense to use the concatenation of `name` and `description`.
- `PersonCard` currently renders the tasks the same way it was rendering the tags. The rendered tasks are currently sorted in increasing lexicographical order of `description`. Moving on, we will be adding `name` to `Task`, after which it makes more sense to sort the tasks by `name` instead.
- `TASK_NUMBER` currently refers to the index of the tasks in `TaskList`. We will need to separately maintain a filtered view of tasks and have `TASK_NUMBER` refer to this list instead.
- The sample data used for testing and preview purposes are still sample tags (e.g. `friends`, `colleagues`). Moving on, we can change these sample tags to sample task names instead (e.g. `prepare-presentation`, `write-report`).
- UG is to be updated to reflect the replacement of `tags` with `tasks`, and to document the new `assign` command.

This PR is linked to #5.

### CODE REVIEW

**Review by Yskie — APPROVED** [review]
Looks good to me!

**Review by nobodyishappy — APPROVED** [review]
Looks great to me!

**Review by Kaya3842 — COMMENTED** [review]
LGTM!

**Review by breezetall — APPROVED** [review]
Looks good to me!

**Pull request merged**
