### PR TITLE
Implement mark and unmark for tasks

### PR DESCRIPTION
**Pull request by nobodyishappy**
# The `MarkTask` Command

The `marktask` command mark tasks as done. The command has the following format:

```
marktask TASK_INDEX
```

Parameter: `TASK_INDEX`

- Must be a numeric string representing a number between 1 and total number of tasks.
- If the value is not acceptable, the error message `The task index provided is invalid` is displayed.

If the task is already marked, the command is still accepted and succeeds.

## Things to note
- `marktask` does not remove the task from the person.

# The `UnmarkTask` Command

The `unmarktask` command mark tasks as undone. The command has the following format:

```
unmarktask TASK_INDEX
```

Parameter: `TASK_INDEX`

- Must be a numeric string representing a number between 1 and total number of tasks.
- If the value is not acceptable, the error message `The task index provided is invalid` is displayed.

If the task is already unmarked, the command is still accepted and succeeds.

This PR is linked to #6.

### CODE REVIEW

**Review by breezetall — APPROVED** [review]
Looks great to me!

**Review by Kaya3842 — APPROVED** [review]
The code is neat and clean. Approved!

**Comment by chin-herng** [comment]
LGTM!

**Review by chin-herng — APPROVED** [review]
LGTM so far! Do modify the UI to display whether a task is done.

**Comment by Yskie** [comment]
Looks good to me!

**Review by Yskie — APPROVED** [review]

**Review by breezetall — APPROVED** [review]
I like that you have created a util class to better facilitate our testing. The code looks good!

**Pull request merged**
